### ISSUE TITLE
URL 설계

### ISSUE THREAD

**Issue by jmkim648** [OrmiFinal/gluv#12]
## 요구사항
RESTful API 설계
자원과 Method 명시
Method에 필요한 사용자의 권한도 같이 명시

**Comment by ghost** [comment]
URL 설계 작업 완료했습니다. 
리뷰 부탁드립니다.
@jmkim648 @sengwoong @dwanGim 

### URL 명세

| URL | 설명 | GET | POST | PUT | DEL | Auth | Permit |
| --- | --- | --- | --- | --- | --- | --- | --- |
| / | Index  | ✔️ |  |  |  |  |  |
| /users/login/ | 로그인   |  | ✔️ |  |  |  |  |
| /users/logout/ | 로그아웃 |  | ✔️ |  |  | ✔️ |  |
| /users/signup/ | 회원 가입 |  | ✔️ |  |  |  |  |
| /users/profile/ | 프로필 수정 |  |  | ✔️ |  | ✔️ | ✔️ |
| /users/{user_id}/profile/ | 프로필 조회 | ✔️ |  |  |  | ✔️ |  |
| /users/deactivate/ | 회원 탈퇴 |  |  |  | ✔️ | ✔️ |  |
| /token/refresh/ | 토큰 갱신 |  | ✔️ |  |  | ✔️ | ✔️ |
| /token/verify/ | 토큰 검증 |  | ✔️ |  |  |  |  |
| /book/recent/ | 최근 도서 정보 조회 | ✔️ |  |  |  |  |  |
| /notification/ | 알림 목록 조회 | ✔️ |  |  |  | ✔️ |  |
| /notification/read/ | 알림 읽기 |  |  | ✔️ |  | ✔️ |  |
| /notification/unread/ | 알림 조회 | ✔️ |  |  |  | ✔️ |  |
| /posts/ | 게시글 생성 |  | ✔️ |  |  | ✔️ |  |
| /posts/ | 게시글 목록 반환 | ✔️ |  |  |  |  |  |
| /posts/notices/ | 공지사항 목록 조회 | ✔️ |  |  |  |  |  |
| /posts/hot/ | 인기 게시글 조회 | ✔️ |  |  |  |  |  |
| /posts/{post_id}/ | 게시글 상세 조회 | ✔️ |  |  |  |  |  |
| /posts/{post_id}/ | 게시글 수정 |  |  | ✔️ |  | ✔️ | ✔️ |
| /posts/{post_id}/ | 게시글 삭제 |  |  |  | ✔️ | ✔️ | ✔️ |
| /recruits/ | 게시글 목록 조회 | ✔️ |  |  |  |  |  |
| /recruits/hot/ | 인기 모집 게시글 조회 | ✔️ |  |  |  |  |  |
| /recruits/{recruit_id}/ | 모집 게시글 상세 조회 | ✔️ |  |  |  |  |  |
| /recruits/ | 모집 게시글 생성 |  | ✔️ |  |  | ✔️ |  |
| /recruits/{recruit_id}/ | 모집 게시글 수정 |  |  |  | ✔️ | ✔️ | ✔️ |
| /recruits/{recruit_id}/ | 모집 게시글 삭제 |  |  |  | ✔️ | ✔️ | ✔️ |
| /recruits/{recruit_id}/apply/ | 모임 참가 신청 |  | ✔️ |  |  | ✔️ |  |
| /teams/ | 모임 목록 조회 | ✔️ |  |  |  |  |  |
| /teams/{team_id}/ | 모임 정보 조회 | ✔️ |  |  |  |  |  |
| /teams/{team_id}/ | 모임 정보 변경 |  |  | ✔️ |  | ✔️ | ✔️ |
| /teams/{team_id}/join/ | 구성원 신청 승인 |  | ✔️ |  |  | ✔️ | ✔️ |
| /teams/{team_id}/leave/ | 모임 나가기 |  | ✔️ |  |  | ✔️ | ✔️ |
| /teams/{team_id}/kick/ | 구성원 추방 |  | ✔️ |  |  | ✔️ | ✔️ |
| /teams/{team_id}/leader/ | 모임 리더 변경 |  |  | ✔️ |  | ✔️ | ✔️ |
| /teams/{team_id}/ | 모임 삭제 |  |  |  | ✔️ | ✔️ | ✔️ |
| /schedule/{schedule_id}/ | 일정 변경 |  |  | ✔️ |  | ✔️ | ✔️ |
| /comments/ | 댓글 작성 |  | ✔️ |  |  | ✔️ |  |
| /comments/{comment_id}/ | 댓글 수정 |  |  | ✔️ |  | ✔️ | ✔️ |
| /comments/{comment_id}/ | 댓글 삭제 |  |  |  | ✔️ | ✔️ | ✔️ |
| /comments/ | 댓글 목록 조회 | ✔️ |  |  |  |  |  |
| /like/ | 추천 등록 |  | ✔️ |  |  | ✔️ |  |
| /like/ | 추천 삭제 |  |  |  | ✔️ | ✔️ |  |
| /chatroom/ | 채팅방 조회 | ✔️ |  |  |  | ✔️ |  |
| /report/ | 신고하기 |  | ✔️ |  |  | ✔️ |  |

**Comment by jmkim648** [comment]
감사합니다. 고생하셨습니다!
몇 가지 질문드립니다. 아직 URL 명세가 생소하다보니 의도 파악이 안 된 경우가 있을 수도 있습니다 ㅠ

```
1.
지난번 회의를 통해 랜딩페이지를 작성하기로 했던 것으로 기억합니다.
`/`를 Index로 두어야 할 지, 그렇다면 랜딩페이지의 URL을 어떻게 해야할 지 궁금합니다.

2.
부트캠프 강의 내용 중 API 설계에서, logout의 경우 프론트에서 쿠키 혹은 로컬스토리지에 저장한 토큰을 삭제하는 것만으로 처리할 수 있기 때문에 POST요청을 안 할 수도 있다는 내용이 있었기 때문에 헷갈리네요.

혹시 logout의 POST요청의 경우 어떠한 특별한 과정이 있는지 궁금합니다.

Notion의 내용을 보면 로그아웃에 성공했다는 것을 서버로 보내는 것으로 이해했습니다. 혹시 맞을까요? 맞다면 로그아웃에 성공했다는 것을 백엔드 서버에서 왜 알아야 하는지 궁금합니다!

3. 
/notification/ (알림 목록 조회)
/notification/unread/ (알림 조회)

이 두 항목의 경우 /notification은 알림의 모든 목록 조회, /notification/unread는 미확인 알림 조회가 맞을까요?
만약 맞다면 알림 조회라는 설명이 명시적으로 와 닿지 않는 것 같습니다.

4.
다른 항목에서는 GET 메소드에서 '조회'라고 명시되어 있는 반면 posts에서는 '반환'이라고 되어 있습니다. 혹시 의미가 있는 명명일까요?

5.
모임 나가기, 모임 추방의 경우 구성원(User-Team) 모델의 data를 삭제하는 것이라 DEL메소드 일 것이라고 생각하고 있었습니다. 무언가의 정보를 POST해야하는 것일까요?

5.
/recruits/{recruit_id}/ (모집 게시글 수정)의 메소드가 DEL로 되어있습니다!
```

**Comment by ghost** [comment]
그러네요. 

1. 이전에 React 이야기가 있었어서 혼동된 부분인것 같습니다. 
리액트 사용 여부 등 프론트 설계 확정 이후 변경토록 하겠습니다.

2. JWT 토큰 만료 이전 로그아웃의 경우에 토큰을 차단 리스트에 추가하는 방식으로 로그아웃을 할 수 있습니다.
    * https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6

3. 네. 어느 방향이든 설명이 부족한 것 같습니다.
'모두 확인'이라는 버튼을 통해 제공되는 기능은 2가지로 나눠질 수 있을 것 같습니다. 
회의때 논의해보고 그 결과대로 반영하여 '전체 알림 조회' '읽지 않은 알림 목록 조회' 등으로 변경하겠습니다. 
    1. 전체 알림 보기 
    2. 읽지 않은 전체 알림을 보기 

4. 의견 감사합니다. 조회로 수정처리 했습니다. 혼용되어 표기된 부분이 그대로 들어간 것 같습니다. 

5. DELETE 가 적절해 보입니다. 문서 수정했습니다. 

6. 잘못 표기된 부분 수정했습니다.
