### ISSUE TITLE
Model 구현

### ISSUE THREAD

**Issue by jmkim648** [OrmiFinal/gluv#13]
## 요구사항
ERD를 기반으로 django 프로젝트의 각 models.py 작성
makemigrations, migrate 관련 방침을 정하고 작성

**Comment by ghost** [comment]
Book 모델 작성하여 PR(#29) 했습니다.

**Comment by ghost** [comment]
모델 일감 분배 상황
- 동완
  - User 
- 재민 
  - Like
  - Schedule 

- 담당자 미지정 일감
  - Comment

**Comment by ghost** [comment]
ChatRoom과 ChatRoomMessage 작성하여 PR(#31) 했습니다.

**Comment by ghost** [comment]
Comment는 동완님이 작업 부탁드립니다.
